import os

# Telegram
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# Hunter Settings

MIN_SCORE = 75

VOLUME_MULTIPLIER = 3

MIN_BUYER_POWER = 2

SCAN_INTERVAL = 300
